// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft_peer.proto

#ifndef PROTOBUF_INCLUDED_raft_5fpeer_2eproto
#define PROTOBUF_INCLUDED_raft_5fpeer_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_raft_5fpeer_2eproto

namespace protobuf_raft_5fpeer_2eproto {
// Internal implementation detail -- do not use these members.
  struct TableStruct {
    static const ::google::protobuf::internal::ParseTableField entries[];
    static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
    static const ::google::protobuf::internal::ParseTable schema[5];
    static const ::google::protobuf::internal::FieldMetadata field_metadata[];
    static const ::google::protobuf::internal::SerializationTable serialization_table[];
    static const ::google::protobuf::uint32 offsets[];
  };

  void AddDescriptors();
}  // namespace protobuf_raft_5fpeer_2eproto
class PbAppendEntriesRequest;
class PbAppendEntriesRequestDefaultTypeInternal;
extern PbAppendEntriesRequestDefaultTypeInternal _PbAppendEntriesRequest_default_instance_;

class PbAppendEntriesRequest_Entry;

class PbAppendEntriesRequest_EntryDefaultTypeInternal;

extern PbAppendEntriesRequest_EntryDefaultTypeInternal _PbAppendEntriesRequest_Entry_default_instance_;
class PbAppendEntriesResponse;
class PbAppendEntriesResponseDefaultTypeInternal;
extern PbAppendEntriesResponseDefaultTypeInternal _PbAppendEntriesResponse_default_instance_;
class PbRequestVoteRequest;
class PbRequestVoteRequestDefaultTypeInternal;
extern PbRequestVoteRequestDefaultTypeInternal _PbRequestVoteRequest_default_instance_;
class PbRequestVoteResponse;
class PbRequestVoteResponseDefaultTypeInternal;
extern PbRequestVoteResponseDefaultTypeInternal _PbRequestVoteResponse_default_instance_;
namespace google {
  namespace protobuf {
    template<>
    ::PbAppendEntriesRequest *Arena::CreateMaybeMessage<::PbAppendEntriesRequest>(Arena *);

    template<>
    ::PbAppendEntriesRequest_Entry *Arena::CreateMaybeMessage<::PbAppendEntriesRequest_Entry>(Arena *);

    template<>
    ::PbAppendEntriesResponse *Arena::CreateMaybeMessage<::PbAppendEntriesResponse>(Arena *);

    template<>
    ::PbRequestVoteRequest *Arena::CreateMaybeMessage<::PbRequestVoteRequest>(Arena *);

    template<>
    ::PbRequestVoteResponse *Arena::CreateMaybeMessage<::PbRequestVoteResponse>(Arena *);
  }  // namespace protobuf
}  // namespace google

// ===================================================================

class PbAppendEntriesRequest_Entry
    : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PbAppendEntriesRequest.Entry) */ {
public:
  PbAppendEntriesRequest_Entry();

  virtual ~PbAppendEntriesRequest_Entry();

  PbAppendEntriesRequest_Entry(const PbAppendEntriesRequest_Entry &from);

  inline PbAppendEntriesRequest_Entry &operator=(const PbAppendEntriesRequest_Entry &from) {
    CopyFrom(from);
    return *this;
  }

#if LANG_CXX11

  PbAppendEntriesRequest_Entry(PbAppendEntriesRequest_Entry &&from) noexcept
      : PbAppendEntriesRequest_Entry() {
    *this = ::std::move(from);
  }

  inline PbAppendEntriesRequest_Entry &operator=(PbAppendEntriesRequest_Entry &&from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

#endif

  static const ::google::protobuf::Descriptor *descriptor();

  static const PbAppendEntriesRequest_Entry &default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PbAppendEntriesRequest_Entry *internal_default_instance() {
    return reinterpret_cast<const PbAppendEntriesRequest_Entry *>(
        &_PbAppendEntriesRequest_Entry_default_instance_);
  }

  static constexpr int kIndexInFileMessages =
      0;

  void Swap(PbAppendEntriesRequest_Entry *other);

  friend void swap(PbAppendEntriesRequest_Entry &a, PbAppendEntriesRequest_Entry &b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PbAppendEntriesRequest_Entry *New() const final {
    return CreateMaybeMessage<PbAppendEntriesRequest_Entry>(NULL);
  }

  PbAppendEntriesRequest_Entry *New(::google::protobuf::Arena *arena) const final {
    return CreateMaybeMessage<PbAppendEntriesRequest_Entry>(arena);
  }

  void CopyFrom(const ::google::protobuf::Message &from) final;

  void MergeFrom(const ::google::protobuf::Message &from) final;

  void CopyFrom(const PbAppendEntriesRequest_Entry &from);

  void MergeFrom(const PbAppendEntriesRequest_Entry &from);

  void Clear() final;

  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;

  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream *input) final;

  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream *output) const final;

  ::google::protobuf::uint8 *InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8 *target) const final;

  int GetCachedSize() const final { return _cached_size_.Get(); }

private:
  void SharedCtor();

  void SharedDtor();

  void SetCachedSize(int size) const final;

  void InternalSwap(PbAppendEntriesRequest_Entry *other);

private:
  inline ::google::protobuf::Arena *GetArenaNoVirtual() const {
    return NULL;
  }

  inline void *MaybeArenaPtr() const {
    return NULL;
  }

public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string command = 1;
  void clear_command();

  static const int kCommandFieldNumber = 1;

  const ::std::string &command() const;

  void set_command(const ::std::string &value);

#if LANG_CXX11

  void set_command(::std::string &&value);

#endif

  void set_command(const char *value);

  void set_command(const char *value, size_t size);

  ::std::string *mutable_command();

  ::std::string *release_command();

  void set_allocated_command(::std::string *command);

  // string key = 2;
  void clear_key();

  static const int kKeyFieldNumber = 2;

  const ::std::string &key() const;

  void set_key(const ::std::string &value);

#if LANG_CXX11

  void set_key(::std::string &&value);

#endif

  void set_key(const char *value);

  void set_key(const char *value, size_t size);

  ::std::string *mutable_key();

  ::std::string *release_key();

  void set_allocated_key(::std::string *key);

  // string val = 3;
  void clear_val();

  static const int kValFieldNumber = 3;

  const ::std::string &val() const;

  void set_val(const ::std::string &value);

#if LANG_CXX11

  void set_val(::std::string &&value);

#endif

  void set_val(const char *value);

  void set_val(const char *value, size_t size);

  ::std::string *mutable_val();

  ::std::string *release_val();

  void set_allocated_val(::std::string *val);

  // @@protoc_insertion_point(class_scope:PbAppendEntriesRequest.Entry)
private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr command_;
  ::google::protobuf::internal::ArenaStringPtr key_;
  ::google::protobuf::internal::ArenaStringPtr val_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_raft_5fpeer_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PbAppendEntriesRequest
    : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PbAppendEntriesRequest) */ {
public:
  PbAppendEntriesRequest();

  virtual ~PbAppendEntriesRequest();

  PbAppendEntriesRequest(const PbAppendEntriesRequest &from);

  inline PbAppendEntriesRequest &operator=(const PbAppendEntriesRequest &from) {
    CopyFrom(from);
    return *this;
  }

#if LANG_CXX11

  PbAppendEntriesRequest(PbAppendEntriesRequest &&from) noexcept
      : PbAppendEntriesRequest() {
    *this = ::std::move(from);
  }

  inline PbAppendEntriesRequest &operator=(PbAppendEntriesRequest &&from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

#endif

  static const ::google::protobuf::Descriptor *descriptor();

  static const PbAppendEntriesRequest &default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PbAppendEntriesRequest *internal_default_instance() {
    return reinterpret_cast<const PbAppendEntriesRequest *>(
        &_PbAppendEntriesRequest_default_instance_);
  }

  static constexpr int kIndexInFileMessages =
      1;

  void Swap(PbAppendEntriesRequest *other);

  friend void swap(PbAppendEntriesRequest &a, PbAppendEntriesRequest &b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PbAppendEntriesRequest *New() const final {
    return CreateMaybeMessage<PbAppendEntriesRequest>(NULL);
  }

  PbAppendEntriesRequest *New(::google::protobuf::Arena *arena) const final {
    return CreateMaybeMessage<PbAppendEntriesRequest>(arena);
  }

  void CopyFrom(const ::google::protobuf::Message &from) final;

  void MergeFrom(const ::google::protobuf::Message &from) final;

  void CopyFrom(const PbAppendEntriesRequest &from);

  void MergeFrom(const PbAppendEntriesRequest &from);

  void Clear() final;

  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;

  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream *input) final;

  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream *output) const final;

  ::google::protobuf::uint8 *InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8 *target) const final;

  int GetCachedSize() const final { return _cached_size_.Get(); }

private:
  void SharedCtor();

  void SharedDtor();

  void SetCachedSize(int size) const final;

  void InternalSwap(PbAppendEntriesRequest *other);

private:
  inline ::google::protobuf::Arena *GetArenaNoVirtual() const {
    return NULL;
  }

  inline void *MaybeArenaPtr() const {
    return NULL;
  }

public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef PbAppendEntriesRequest_Entry Entry;

  // accessors -------------------------------------------------------

  // repeated .PbAppendEntriesRequest.Entry entries = 5;
  int entries_size() const;

  void clear_entries();

  static const int kEntriesFieldNumber = 5;

  ::PbAppendEntriesRequest_Entry *mutable_entries(int index);

  ::google::protobuf::RepeatedPtrField<::PbAppendEntriesRequest_Entry> *
  mutable_entries();

  const ::PbAppendEntriesRequest_Entry &entries(int index) const;

  ::PbAppendEntriesRequest_Entry *add_entries();

  const ::google::protobuf::RepeatedPtrField<::PbAppendEntriesRequest_Entry> &
  entries() const;

  // string leaderId = 2;
  void clear_leaderid();

  static const int kLeaderIdFieldNumber = 2;

  const ::std::string &leaderid() const;

  void set_leaderid(const ::std::string &value);

#if LANG_CXX11

  void set_leaderid(::std::string &&value);

#endif

  void set_leaderid(const char *value);

  void set_leaderid(const char *value, size_t size);

  ::std::string *mutable_leaderid();

  ::std::string *release_leaderid();

  void set_allocated_leaderid(::std::string *leaderid);

  // int64 term = 1;
  void clear_term();

  static const int kTermFieldNumber = 1;

  ::google::protobuf::int64 term() const;

  void set_term(::google::protobuf::int64 value);

  // int64 prevLogIndex = 3;
  void clear_prevlogindex();

  static const int kPrevLogIndexFieldNumber = 3;

  ::google::protobuf::int64 prevlogindex() const;

  void set_prevlogindex(::google::protobuf::int64 value);

  // int64 prevLogTerm = 4;
  void clear_prevlogterm();

  static const int kPrevLogTermFieldNumber = 4;

  ::google::protobuf::int64 prevlogterm() const;

  void set_prevlogterm(::google::protobuf::int64 value);

  // int64 leaderCommit = 6;
  void clear_leadercommit();

  static const int kLeaderCommitFieldNumber = 6;

  ::google::protobuf::int64 leadercommit() const;

  void set_leadercommit(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:PbAppendEntriesRequest)
private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField<::PbAppendEntriesRequest_Entry> entries_;
  ::google::protobuf::internal::ArenaStringPtr leaderid_;
  ::google::protobuf::int64 term_;
  ::google::protobuf::int64 prevlogindex_;
  ::google::protobuf::int64 prevlogterm_;
  ::google::protobuf::int64 leadercommit_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_raft_5fpeer_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PbAppendEntriesResponse
    : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PbAppendEntriesResponse) */ {
public:
  PbAppendEntriesResponse();

  virtual ~PbAppendEntriesResponse();

  PbAppendEntriesResponse(const PbAppendEntriesResponse &from);

  inline PbAppendEntriesResponse &operator=(const PbAppendEntriesResponse &from) {
    CopyFrom(from);
    return *this;
  }

#if LANG_CXX11

  PbAppendEntriesResponse(PbAppendEntriesResponse &&from) noexcept
      : PbAppendEntriesResponse() {
    *this = ::std::move(from);
  }

  inline PbAppendEntriesResponse &operator=(PbAppendEntriesResponse &&from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

#endif

  static const ::google::protobuf::Descriptor *descriptor();

  static const PbAppendEntriesResponse &default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PbAppendEntriesResponse *internal_default_instance() {
    return reinterpret_cast<const PbAppendEntriesResponse *>(
        &_PbAppendEntriesResponse_default_instance_);
  }

  static constexpr int kIndexInFileMessages =
      2;

  void Swap(PbAppendEntriesResponse *other);

  friend void swap(PbAppendEntriesResponse &a, PbAppendEntriesResponse &b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PbAppendEntriesResponse *New() const final {
    return CreateMaybeMessage<PbAppendEntriesResponse>(NULL);
  }

  PbAppendEntriesResponse *New(::google::protobuf::Arena *arena) const final {
    return CreateMaybeMessage<PbAppendEntriesResponse>(arena);
  }

  void CopyFrom(const ::google::protobuf::Message &from) final;

  void MergeFrom(const ::google::protobuf::Message &from) final;

  void CopyFrom(const PbAppendEntriesResponse &from);

  void MergeFrom(const PbAppendEntriesResponse &from);

  void Clear() final;

  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;

  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream *input) final;

  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream *output) const final;

  ::google::protobuf::uint8 *InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8 *target) const final;

  int GetCachedSize() const final { return _cached_size_.Get(); }

private:
  void SharedCtor();

  void SharedDtor();

  void SetCachedSize(int size) const final;

  void InternalSwap(PbAppendEntriesResponse *other);

private:
  inline ::google::protobuf::Arena *GetArenaNoVirtual() const {
    return NULL;
  }

  inline void *MaybeArenaPtr() const {
    return NULL;
  }

public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int64 term = 1;
  void clear_term();

  static const int kTermFieldNumber = 1;

  ::google::protobuf::int64 term() const;

  void set_term(::google::protobuf::int64 value);

  // bool success = 2;
  void clear_success();

  static const int kSuccessFieldNumber = 2;

  bool success() const;

  void set_success(bool value);

  // @@protoc_insertion_point(class_scope:PbAppendEntriesResponse)
private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int64 term_;
  bool success_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_raft_5fpeer_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PbRequestVoteRequest
    : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PbRequestVoteRequest) */ {
public:
  PbRequestVoteRequest();

  virtual ~PbRequestVoteRequest();

  PbRequestVoteRequest(const PbRequestVoteRequest &from);

  inline PbRequestVoteRequest &operator=(const PbRequestVoteRequest &from) {
    CopyFrom(from);
    return *this;
  }

#if LANG_CXX11

  PbRequestVoteRequest(PbRequestVoteRequest &&from) noexcept
      : PbRequestVoteRequest() {
    *this = ::std::move(from);
  }

  inline PbRequestVoteRequest &operator=(PbRequestVoteRequest &&from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

#endif

  static const ::google::protobuf::Descriptor *descriptor();

  static const PbRequestVoteRequest &default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PbRequestVoteRequest *internal_default_instance() {
    return reinterpret_cast<const PbRequestVoteRequest *>(
        &_PbRequestVoteRequest_default_instance_);
  }

  static constexpr int kIndexInFileMessages =
      3;

  void Swap(PbRequestVoteRequest *other);

  friend void swap(PbRequestVoteRequest &a, PbRequestVoteRequest &b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PbRequestVoteRequest *New() const final {
    return CreateMaybeMessage<PbRequestVoteRequest>(NULL);
  }

  PbRequestVoteRequest *New(::google::protobuf::Arena *arena) const final {
    return CreateMaybeMessage<PbRequestVoteRequest>(arena);
  }

  void CopyFrom(const ::google::protobuf::Message &from) final;

  void MergeFrom(const ::google::protobuf::Message &from) final;

  void CopyFrom(const PbRequestVoteRequest &from);

  void MergeFrom(const PbRequestVoteRequest &from);

  void Clear() final;

  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;

  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream *input) final;

  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream *output) const final;

  ::google::protobuf::uint8 *InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8 *target) const final;

  int GetCachedSize() const final { return _cached_size_.Get(); }

private:
  void SharedCtor();

  void SharedDtor();

  void SetCachedSize(int size) const final;

  void InternalSwap(PbRequestVoteRequest *other);

private:
  inline ::google::protobuf::Arena *GetArenaNoVirtual() const {
    return NULL;
  }

  inline void *MaybeArenaPtr() const {
    return NULL;
  }

public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string candidateId = 2;
  void clear_candidateid();

  static const int kCandidateIdFieldNumber = 2;

  const ::std::string &candidateid() const;

  void set_candidateid(const ::std::string &value);

#if LANG_CXX11

  void set_candidateid(::std::string &&value);

#endif

  void set_candidateid(const char *value);

  void set_candidateid(const char *value, size_t size);

  ::std::string *mutable_candidateid();

  ::std::string *release_candidateid();

  void set_allocated_candidateid(::std::string *candidateid);

  // int64 term = 1;
  void clear_term();

  static const int kTermFieldNumber = 1;

  ::google::protobuf::int64 term() const;

  void set_term(::google::protobuf::int64 value);

  // int64 lastLogIndex = 3;
  void clear_lastlogindex();

  static const int kLastLogIndexFieldNumber = 3;

  ::google::protobuf::int64 lastlogindex() const;

  void set_lastlogindex(::google::protobuf::int64 value);

  // int64 lastLogTerm = 4;
  void clear_lastlogterm();

  static const int kLastLogTermFieldNumber = 4;

  ::google::protobuf::int64 lastlogterm() const;

  void set_lastlogterm(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:PbRequestVoteRequest)
private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr candidateid_;
  ::google::protobuf::int64 term_;
  ::google::protobuf::int64 lastlogindex_;
  ::google::protobuf::int64 lastlogterm_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_raft_5fpeer_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PbRequestVoteResponse
    : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PbRequestVoteResponse) */ {
public:
  PbRequestVoteResponse();

  virtual ~PbRequestVoteResponse();

  PbRequestVoteResponse(const PbRequestVoteResponse &from);

  inline PbRequestVoteResponse &operator=(const PbRequestVoteResponse &from) {
    CopyFrom(from);
    return *this;
  }

#if LANG_CXX11

  PbRequestVoteResponse(PbRequestVoteResponse &&from) noexcept
      : PbRequestVoteResponse() {
    *this = ::std::move(from);
  }

  inline PbRequestVoteResponse &operator=(PbRequestVoteResponse &&from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

#endif

  static const ::google::protobuf::Descriptor *descriptor();

  static const PbRequestVoteResponse &default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PbRequestVoteResponse *internal_default_instance() {
    return reinterpret_cast<const PbRequestVoteResponse *>(
        &_PbRequestVoteResponse_default_instance_);
  }

  static constexpr int kIndexInFileMessages =
      4;

  void Swap(PbRequestVoteResponse *other);

  friend void swap(PbRequestVoteResponse &a, PbRequestVoteResponse &b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PbRequestVoteResponse *New() const final {
    return CreateMaybeMessage<PbRequestVoteResponse>(NULL);
  }

  PbRequestVoteResponse *New(::google::protobuf::Arena *arena) const final {
    return CreateMaybeMessage<PbRequestVoteResponse>(arena);
  }

  void CopyFrom(const ::google::protobuf::Message &from) final;

  void MergeFrom(const ::google::protobuf::Message &from) final;

  void CopyFrom(const PbRequestVoteResponse &from);

  void MergeFrom(const PbRequestVoteResponse &from);

  void Clear() final;

  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;

  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream *input) final;

  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream *output) const final;

  ::google::protobuf::uint8 *InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8 *target) const final;

  int GetCachedSize() const final { return _cached_size_.Get(); }

private:
  void SharedCtor();

  void SharedDtor();

  void SetCachedSize(int size) const final;

  void InternalSwap(PbRequestVoteResponse *other);

private:
  inline ::google::protobuf::Arena *GetArenaNoVirtual() const {
    return NULL;
  }

  inline void *MaybeArenaPtr() const {
    return NULL;
  }

public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int64 term = 1;
  void clear_term();

  static const int kTermFieldNumber = 1;

  ::google::protobuf::int64 term() const;

  void set_term(::google::protobuf::int64 value);

  // bool voteGranted = 2;
  void clear_votegranted();

  static const int kVoteGrantedFieldNumber = 2;

  bool votegranted() const;

  void set_votegranted(bool value);

  // @@protoc_insertion_point(class_scope:PbRequestVoteResponse)
private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int64 term_;
  bool votegranted_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_raft_5fpeer_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PbAppendEntriesRequest_Entry

// string command = 1;
inline void PbAppendEntriesRequest_Entry::clear_command() {
  command_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

inline const ::std::string &PbAppendEntriesRequest_Entry::command() const {
  // @@protoc_insertion_point(field_get:PbAppendEntriesRequest.Entry.command)
  return command_.GetNoArena();
}

inline void PbAppendEntriesRequest_Entry::set_command(const ::std::string &value) {

  command_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PbAppendEntriesRequest.Entry.command)
}

#if LANG_CXX11

inline void PbAppendEntriesRequest_Entry::set_command(::std::string &&value) {

  command_.SetNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:PbAppendEntriesRequest.Entry.command)
}

#endif

inline void PbAppendEntriesRequest_Entry::set_command(const char *value) {
      GOOGLE_DCHECK(value != NULL);

  command_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PbAppendEntriesRequest.Entry.command)
}

inline void PbAppendEntriesRequest_Entry::set_command(const char *value, size_t size) {

  command_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
                      ::std::string(reinterpret_cast<const char *>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PbAppendEntriesRequest.Entry.command)
}

inline ::std::string *PbAppendEntriesRequest_Entry::mutable_command() {

  // @@protoc_insertion_point(field_mutable:PbAppendEntriesRequest.Entry.command)
  return command_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

inline ::std::string *PbAppendEntriesRequest_Entry::release_command() {
  // @@protoc_insertion_point(field_release:PbAppendEntriesRequest.Entry.command)

  return command_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

inline void PbAppendEntriesRequest_Entry::set_allocated_command(::std::string *command) {
  if (command != NULL) {

  } else {

  }
  command_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), command);
  // @@protoc_insertion_point(field_set_allocated:PbAppendEntriesRequest.Entry.command)
}

// string key = 2;
inline void PbAppendEntriesRequest_Entry::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

inline const ::std::string &PbAppendEntriesRequest_Entry::key() const {
  // @@protoc_insertion_point(field_get:PbAppendEntriesRequest.Entry.key)
  return key_.GetNoArena();
}

inline void PbAppendEntriesRequest_Entry::set_key(const ::std::string &value) {

  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PbAppendEntriesRequest.Entry.key)
}

#if LANG_CXX11

inline void PbAppendEntriesRequest_Entry::set_key(::std::string &&value) {

  key_.SetNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:PbAppendEntriesRequest.Entry.key)
}

#endif

inline void PbAppendEntriesRequest_Entry::set_key(const char *value) {
      GOOGLE_DCHECK(value != NULL);

  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PbAppendEntriesRequest.Entry.key)
}

inline void PbAppendEntriesRequest_Entry::set_key(const char *value, size_t size) {

  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
                  ::std::string(reinterpret_cast<const char *>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PbAppendEntriesRequest.Entry.key)
}

inline ::std::string *PbAppendEntriesRequest_Entry::mutable_key() {

  // @@protoc_insertion_point(field_mutable:PbAppendEntriesRequest.Entry.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

inline ::std::string *PbAppendEntriesRequest_Entry::release_key() {
  // @@protoc_insertion_point(field_release:PbAppendEntriesRequest.Entry.key)

  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

inline void PbAppendEntriesRequest_Entry::set_allocated_key(::std::string *key) {
  if (key != NULL) {

  } else {

  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:PbAppendEntriesRequest.Entry.key)
}

// string val = 3;
inline void PbAppendEntriesRequest_Entry::clear_val() {
  val_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

inline const ::std::string &PbAppendEntriesRequest_Entry::val() const {
  // @@protoc_insertion_point(field_get:PbAppendEntriesRequest.Entry.val)
  return val_.GetNoArena();
}

inline void PbAppendEntriesRequest_Entry::set_val(const ::std::string &value) {

  val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PbAppendEntriesRequest.Entry.val)
}

#if LANG_CXX11

inline void PbAppendEntriesRequest_Entry::set_val(::std::string &&value) {

  val_.SetNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:PbAppendEntriesRequest.Entry.val)
}

#endif

inline void PbAppendEntriesRequest_Entry::set_val(const char *value) {
      GOOGLE_DCHECK(value != NULL);

  val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PbAppendEntriesRequest.Entry.val)
}

inline void PbAppendEntriesRequest_Entry::set_val(const char *value, size_t size) {

  val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
                  ::std::string(reinterpret_cast<const char *>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PbAppendEntriesRequest.Entry.val)
}

inline ::std::string *PbAppendEntriesRequest_Entry::mutable_val() {

  // @@protoc_insertion_point(field_mutable:PbAppendEntriesRequest.Entry.val)
  return val_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

inline ::std::string *PbAppendEntriesRequest_Entry::release_val() {
  // @@protoc_insertion_point(field_release:PbAppendEntriesRequest.Entry.val)

  return val_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

inline void PbAppendEntriesRequest_Entry::set_allocated_val(::std::string *val) {
  if (val != NULL) {

  } else {

  }
  val_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), val);
  // @@protoc_insertion_point(field_set_allocated:PbAppendEntriesRequest.Entry.val)
}

// -------------------------------------------------------------------

// PbAppendEntriesRequest

// int64 term = 1;
inline void PbAppendEntriesRequest::clear_term() {
  term_ = GOOGLE_LONGLONG(0);
}

inline ::google::protobuf::int64 PbAppendEntriesRequest::term() const {
  // @@protoc_insertion_point(field_get:PbAppendEntriesRequest.term)
  return term_;
}

inline void PbAppendEntriesRequest::set_term(::google::protobuf::int64 value) {

  term_ = value;
  // @@protoc_insertion_point(field_set:PbAppendEntriesRequest.term)
}

// string leaderId = 2;
inline void PbAppendEntriesRequest::clear_leaderid() {
  leaderid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

inline const ::std::string &PbAppendEntriesRequest::leaderid() const {
  // @@protoc_insertion_point(field_get:PbAppendEntriesRequest.leaderId)
  return leaderid_.GetNoArena();
}

inline void PbAppendEntriesRequest::set_leaderid(const ::std::string &value) {

  leaderid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PbAppendEntriesRequest.leaderId)
}
#if LANG_CXX11

inline void PbAppendEntriesRequest::set_leaderid(::std::string &&value) {

  leaderid_.SetNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:PbAppendEntriesRequest.leaderId)
}
#endif

inline void PbAppendEntriesRequest::set_leaderid(const char *value) {
      GOOGLE_DCHECK(value != NULL);

  leaderid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PbAppendEntriesRequest.leaderId)
}

inline void PbAppendEntriesRequest::set_leaderid(const char *value, size_t size) {

  leaderid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
                       ::std::string(reinterpret_cast<const char *>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PbAppendEntriesRequest.leaderId)
}

inline ::std::string *PbAppendEntriesRequest::mutable_leaderid() {

  // @@protoc_insertion_point(field_mutable:PbAppendEntriesRequest.leaderId)
  return leaderid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

inline ::std::string *PbAppendEntriesRequest::release_leaderid() {
  // @@protoc_insertion_point(field_release:PbAppendEntriesRequest.leaderId)

  return leaderid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

inline void PbAppendEntriesRequest::set_allocated_leaderid(::std::string *leaderid) {
  if (leaderid != NULL) {

  } else {

  }
  leaderid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), leaderid);
  // @@protoc_insertion_point(field_set_allocated:PbAppendEntriesRequest.leaderId)
}

// int64 prevLogIndex = 3;
inline void PbAppendEntriesRequest::clear_prevlogindex() {
  prevlogindex_ = GOOGLE_LONGLONG(0);
}

inline ::google::protobuf::int64 PbAppendEntriesRequest::prevlogindex() const {
  // @@protoc_insertion_point(field_get:PbAppendEntriesRequest.prevLogIndex)
  return prevlogindex_;
}

inline void PbAppendEntriesRequest::set_prevlogindex(::google::protobuf::int64 value) {

  prevlogindex_ = value;
  // @@protoc_insertion_point(field_set:PbAppendEntriesRequest.prevLogIndex)
}

// int64 prevLogTerm = 4;
inline void PbAppendEntriesRequest::clear_prevlogterm() {
  prevlogterm_ = GOOGLE_LONGLONG(0);
}

inline ::google::protobuf::int64 PbAppendEntriesRequest::prevlogterm() const {
  // @@protoc_insertion_point(field_get:PbAppendEntriesRequest.prevLogTerm)
  return prevlogterm_;
}

inline void PbAppendEntriesRequest::set_prevlogterm(::google::protobuf::int64 value) {

  prevlogterm_ = value;
  // @@protoc_insertion_point(field_set:PbAppendEntriesRequest.prevLogTerm)
}

// repeated .PbAppendEntriesRequest.Entry entries = 5;
inline int PbAppendEntriesRequest::entries_size() const {
  return entries_.size();
}
inline void PbAppendEntriesRequest::clear_entries() {
  entries_.Clear();
}

inline ::PbAppendEntriesRequest_Entry *PbAppendEntriesRequest::mutable_entries(int index) {
  // @@protoc_insertion_point(field_mutable:PbAppendEntriesRequest.entries)
  return entries_.Mutable(index);
}

inline ::google::protobuf::RepeatedPtrField<::PbAppendEntriesRequest_Entry> *
PbAppendEntriesRequest::mutable_entries() {
  // @@protoc_insertion_point(field_mutable_list:PbAppendEntriesRequest.entries)
  return &entries_;
}

inline const ::PbAppendEntriesRequest_Entry &PbAppendEntriesRequest::entries(int index) const {
  // @@protoc_insertion_point(field_get:PbAppendEntriesRequest.entries)
  return entries_.Get(index);
}

inline ::PbAppendEntriesRequest_Entry *PbAppendEntriesRequest::add_entries() {
  // @@protoc_insertion_point(field_add:PbAppendEntriesRequest.entries)
  return entries_.Add();
}

inline const ::google::protobuf::RepeatedPtrField<::PbAppendEntriesRequest_Entry> &
PbAppendEntriesRequest::entries() const {
  // @@protoc_insertion_point(field_list:PbAppendEntriesRequest.entries)
  return entries_;
}

// int64 leaderCommit = 6;
inline void PbAppendEntriesRequest::clear_leadercommit() {
  leadercommit_ = GOOGLE_LONGLONG(0);
}

inline ::google::protobuf::int64 PbAppendEntriesRequest::leadercommit() const {
  // @@protoc_insertion_point(field_get:PbAppendEntriesRequest.leaderCommit)
  return leadercommit_;
}

inline void PbAppendEntriesRequest::set_leadercommit(::google::protobuf::int64 value) {

  leadercommit_ = value;
  // @@protoc_insertion_point(field_set:PbAppendEntriesRequest.leaderCommit)
}

// -------------------------------------------------------------------

// PbAppendEntriesResponse

// int64 term = 1;
inline void PbAppendEntriesResponse::clear_term() {
  term_ = GOOGLE_LONGLONG(0);
}

inline ::google::protobuf::int64 PbAppendEntriesResponse::term() const {
  // @@protoc_insertion_point(field_get:PbAppendEntriesResponse.term)
  return term_;
}

inline void PbAppendEntriesResponse::set_term(::google::protobuf::int64 value) {

  term_ = value;
  // @@protoc_insertion_point(field_set:PbAppendEntriesResponse.term)
}

// bool success = 2;
inline void PbAppendEntriesResponse::clear_success() {
  success_ = false;
}
inline bool PbAppendEntriesResponse::success() const {
  // @@protoc_insertion_point(field_get:PbAppendEntriesResponse.success)
  return success_;
}
inline void PbAppendEntriesResponse::set_success(bool value) {

  success_ = value;
  // @@protoc_insertion_point(field_set:PbAppendEntriesResponse.success)
}

// -------------------------------------------------------------------

// PbRequestVoteRequest

// int64 term = 1;
inline void PbRequestVoteRequest::clear_term() {
  term_ = GOOGLE_LONGLONG(0);
}

inline ::google::protobuf::int64 PbRequestVoteRequest::term() const {
  // @@protoc_insertion_point(field_get:PbRequestVoteRequest.term)
  return term_;
}

inline void PbRequestVoteRequest::set_term(::google::protobuf::int64 value) {

  term_ = value;
  // @@protoc_insertion_point(field_set:PbRequestVoteRequest.term)
}

// string candidateId = 2;
inline void PbRequestVoteRequest::clear_candidateid() {
  candidateid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

inline const ::std::string &PbRequestVoteRequest::candidateid() const {
  // @@protoc_insertion_point(field_get:PbRequestVoteRequest.candidateId)
  return candidateid_.GetNoArena();
}

inline void PbRequestVoteRequest::set_candidateid(const ::std::string &value) {

  candidateid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PbRequestVoteRequest.candidateId)
}
#if LANG_CXX11

inline void PbRequestVoteRequest::set_candidateid(::std::string &&value) {

  candidateid_.SetNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:PbRequestVoteRequest.candidateId)
}
#endif

inline void PbRequestVoteRequest::set_candidateid(const char *value) {
      GOOGLE_DCHECK(value != NULL);

  candidateid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PbRequestVoteRequest.candidateId)
}

inline void PbRequestVoteRequest::set_candidateid(const char *value, size_t size) {

  candidateid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
                          ::std::string(reinterpret_cast<const char *>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PbRequestVoteRequest.candidateId)
}

inline ::std::string *PbRequestVoteRequest::mutable_candidateid() {

  // @@protoc_insertion_point(field_mutable:PbRequestVoteRequest.candidateId)
  return candidateid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

inline ::std::string *PbRequestVoteRequest::release_candidateid() {
  // @@protoc_insertion_point(field_release:PbRequestVoteRequest.candidateId)

  return candidateid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

inline void PbRequestVoteRequest::set_allocated_candidateid(::std::string *candidateid) {
  if (candidateid != NULL) {

  } else {

  }
  candidateid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), candidateid);
  // @@protoc_insertion_point(field_set_allocated:PbRequestVoteRequest.candidateId)
}

// int64 lastLogIndex = 3;
inline void PbRequestVoteRequest::clear_lastlogindex() {
  lastlogindex_ = GOOGLE_LONGLONG(0);
}

inline ::google::protobuf::int64 PbRequestVoteRequest::lastlogindex() const {
  // @@protoc_insertion_point(field_get:PbRequestVoteRequest.lastLogIndex)
  return lastlogindex_;
}

inline void PbRequestVoteRequest::set_lastlogindex(::google::protobuf::int64 value) {

  lastlogindex_ = value;
  // @@protoc_insertion_point(field_set:PbRequestVoteRequest.lastLogIndex)
}

// int64 lastLogTerm = 4;
inline void PbRequestVoteRequest::clear_lastlogterm() {
  lastlogterm_ = GOOGLE_LONGLONG(0);
}

inline ::google::protobuf::int64 PbRequestVoteRequest::lastlogterm() const {
  // @@protoc_insertion_point(field_get:PbRequestVoteRequest.lastLogTerm)
  return lastlogterm_;
}

inline void PbRequestVoteRequest::set_lastlogterm(::google::protobuf::int64 value) {

  lastlogterm_ = value;
  // @@protoc_insertion_point(field_set:PbRequestVoteRequest.lastLogTerm)
}

// -------------------------------------------------------------------

// PbRequestVoteResponse

// int64 term = 1;
inline void PbRequestVoteResponse::clear_term() {
  term_ = GOOGLE_LONGLONG(0);
}

inline ::google::protobuf::int64 PbRequestVoteResponse::term() const {
  // @@protoc_insertion_point(field_get:PbRequestVoteResponse.term)
  return term_;
}

inline void PbRequestVoteResponse::set_term(::google::protobuf::int64 value) {

  term_ = value;
  // @@protoc_insertion_point(field_set:PbRequestVoteResponse.term)
}

// bool voteGranted = 2;
inline void PbRequestVoteResponse::clear_votegranted() {
  votegranted_ = false;
}
inline bool PbRequestVoteResponse::votegranted() const {
  // @@protoc_insertion_point(field_get:PbRequestVoteResponse.voteGranted)
  return votegranted_;
}
inline void PbRequestVoteResponse::set_votegranted(bool value) {

  votegranted_ = value;
  // @@protoc_insertion_point(field_set:PbRequestVoteResponse.voteGranted)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_raft_5fpeer_2eproto
